webcomic_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from webcomic_site.base import views as base_views
from webcomic_site.comic import views as comic_views
from webcomic_site.author import views as author_views

urlpatterns = [
    # homepage routes
    path('', base_views.homepage, name='homepage'),

    # base routes
    path('signup/', base_views.signup, name='signup'),
    path('<username>/signup-success/', base_views.signup_success, name='signup_success'),
    path('activation/<token>/', base_views.user_activation, name='user_activation'),
    path('login/', base_views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', base_views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='base/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', base_views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='base/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('settings/password/', base_views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='base/password_change_done.html'
    ), name='password_change_done'),

    # admin routes
    path('admin/', admin.site.urls),

    # api routes
    path('api/', include('webcomic_site.rest.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_jwt_token),
    path('api-token-verify/', verify_jwt_token),
    path('api-token-refresh/', refresh_jwt_token),

    # ajax routes
    path('ajax/', include('webcomic_site.ajax.urls')),

    # genre routes
    # path('genre/<slug:slug>/', comic_views.GenreDetailView.as_view(), name='genre_detail'),
    path('genre/<slug:slug>/', comic_views.genre_detail, name='genre_detail'),

    # user author routes
    path('profile/<username>/', author_views.AuthorDetailView.as_view(), name='author_detail'),

    # comic routes
    path('comic/create/', comic_views.ComicCreateView.as_view(), name='comic_create'),
    path('<slug:slug>/', comic_views.ComicDetailView.as_view(), name='comic_detail'),
    path('<slug:slug>/author-page/', comic_views.ComicAuthorPageView.as_view(), name='comic_author'),
    path('<slug:slug>/update/', comic_views.ComicUpdateView.as_view(), name='comic_update'),
    path('<slug:slug>/update-state/<int:state>/', comic_views.action_state, name='comic_state'),

    # chapter routes
    path('<slug:comic_slug>/chapter/create/', comic_views.ChapterCreateView.as_view(), name='chapter_create'),
    path('<slug:comic_slug>/<slug:chapter_slug>/', comic_views.ChapterDetailView.as_view(),
         name='chapter_detail'),
    path('<slug:comic_slug>/<slug:chapter_slug>/author-page/', comic_views.ChapterAuthorPageView.as_view(),
         name='chapter_author'),
    path('<slug:comic_slug>/<slug:chapter_slug>/update/', comic_views.ChapterUpdateView.as_view(),
         name='chapter_update'),
    path('<slug:comic_slug>/<slug:chapter_slug>/add-image/', comic_views.ChapterImageCreateView.as_view(),
         name='chapter_add_image'),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webcomic_site/comic/models.py
import os
from base64 import b64encode
from uuid import uuid4

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone

from webcomic_site.base.models import BaseModel
from webcomic_site.tools import get_unique_slug


# Create your models here.
class Genre(BaseModel):
    name = models.CharField(max_length=64, verbose_name="Name")
    slug = models.CharField(max_length=70, verbose_name="Slug", db_index=True, blank=True, null=True)
    description = models.CharField(max_length=160, verbose_name="Description", blank=True, null=True)

    class Meta:
        db_table = settings.DATABASE_TABLE_PREFIX + 'genre'
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == '':
            self.slug = get_unique_slug(Genre, self.name)
        super().save(*args, **kwargs)


def get_upload_comic_path(instance=None):
    path = 'uploads/comic/'
    if instance:
        dirname = b64encode(str(instance.id).encode())
        path += '%s/' % (dirname.decode('utf-8'))
    return path


def upload_comic_banner(instance, filename):
    path = get_upload_comic_path(instance=instance)
    ext = filename.split('.')[-1]
    new_name = 'banner-%s.%s' % (uuid4().hex, ext)
    return os.path.join(path, new_name)


def upload_comic_thumbnail(instance, filename):
    path = get_upload_comic_path(instance=instance)
    ext = filename.split('.')[-1]
    new_name = 'thumbnail-%s.%s' % (uuid4().hex, ext)
    return os.path.join(path, new_name)


class Comic(models.Model):
    STATE = [
        (0, 'Draft'),
        (1, 'Published'),
        (9, 'Archived'),
    ]

    title = models.CharField(max_length=120, verbose_name="Title")
    description = models.CharField(max_length=160, verbose_name="Description")
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT, related_name='comics', verbose_name="Genre")
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='comics', verbose_name="Author")
    slug = models.CharField(max_length=130, unique=True, db_index=True, verbose_name="Slug", blank=True)
    thumbnail = models.ImageField(upload_to=upload_comic_thumbnail, verbose_name="Thumbnail", blank=True, null=True)
    banner = models.ImageField(upload_to=upload_comic_banner, verbose_name="Banner", blank=True, null=True)
    state = models.IntegerField(choices=STATE, verbose_name="State", default=0)
    publish_date = models.DateTimeField(verbose_name="Publish Date", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        db_table = settings.DATABASE_TABLE_PREFIX + 'comic'
        ordering = ['title']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == '':
            self.slug = get_unique_slug(self.title[:24])
        super().save(*args, **kwargs)

    def set_state(self, state):
        self.state = state
        if state == 1:
            self.publish_date = timezone.now()
        self.save()

    def get_direct_url(self):
        return reverse('comic_detail', kwargs={'slug': self.slug})

    def get_author_url(self):
        return reverse('comic_author', kwargs={'slug': self.slug})

    def get_chapter_create_url(self):
        return reverse('chapter_create', kwargs={'comic_slug': self.slug})


def get_upload_chapter_path(instance):
    path = get_upload_comic_path(instance=instance.comic)
    dirname = b64encode(str(instance.id).encode())
    path += 'chapter-%s/' % (dirname.decode('utf-8'))
    return path


def upload_chapter_thumbnail(instance, filename):
    path = get_upload_chapter_path(instance)
    ext = filename.split('.')[-1]
    new_name = 'thumbnail-%s.%s' % (uuid4().hex, ext)
    return os.path.join(path, new_name)


class ComicChapter(models.Model):
    STATE = [
        (0, 'Draft'),
        (1, 'Published'),
        (9, 'Archived'),
    ]

    title = models.CharField(max_length=120, verbose_name="Title")
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE, related_name='chapters', verbose_name="Comic")
    slug = models.CharField(max_length=130, unique=True, db_index=True, verbose_name="Slug", blank=True)
    thumbnail = models.ImageField(upload_to=upload_chapter_thumbnail, verbose_name="Thumbnail", blank=True, null=True)
    state = models.IntegerField(verbose_name="State", choices=STATE, default=0)
    publish_date = models.DateTimeField(verbose_name="Publish Date", blank=True, null=True)
    read = models.IntegerField(verbose_name="Read", default=0)
    sequence = models.IntegerField(verbose_name="Sequence", default=1)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        db_table = settings.DATABASE_TABLE_PREFIX + 'comic_chapter'
        ordering = ['-sequence']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == '':
            self.slug = get_unique_slug(self.title[:24])
        super().save(*args, **kwargs)

    def add_reader(self):
        self.read += 1
        self.save()

    def get_direct_url(self):
        return reverse('chapter_detail', kwargs={'comic_slug': self.comic.slug, 'chapter_slug': self.slug})

    def get_author_url(self):
        return reverse('chapter_author', kwargs={'comic_slug': self.comic.slug, 'chapter_slug': self.slug})


def upload_chapter_image(instance, filename):
    path = get_upload_chapter_path(instance.chapter)
    ext = filename.split('.')[-1]
    new_name = '%s.%s' % (uuid4().hex, ext)
    return os.path.join(path, new_name)


class ChapterImage(models.Model):
    image = models.ImageField(upload_to=upload_chapter_image, verbose_name="Image", null=True, blank=True)
    sequence = models.IntegerField(verbose_name="Sequence", default=1)
    chapter = models.ForeignKey(ComicChapter, on_delete=models.CASCADE, related_name='images', verbose_name="Chapter")
    upload_at = models.DateTimeField(auto_now_add=True, verbose_name="Upload At")

    class Meta:
        ordering = ['sequence']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.chapter.updated_at = timezone.now()
        self.chapter.save()

webcomic_site/comic/templates/comic/author_page.html
{% extends 'layouts/main_layout.html' %}

{% block extra_meta %}<meta name="robots" content="noindex,nofollow">{% endblock %}
{% block title %}Author Page{% endblock %}

{% block content %}
  <div class="container my-3" id="main-content">
    <div class="row">
      <div class="col col-md-3 col-12">
        <div class="card">
          <div class="card-header">{{ comic.title }}</div>
          <div class="card-body">
            <a href="{% url 'comic_update' slug=comic.slug %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'chapter_create' comic_slug=comic.slug %}" class="btn btn-primary">New Chapter</a>
            <h5>Genre: <a href="{% url 'genre_detail' slug=comic.genre.slug %}">{{ comic.genre.name }}</a></h5>
            Thumbnail:
            {% if comic.thumbnail %}
              <img src="{{ comic.thumbnail.url }}" class="img-fluid">
            {% else %}
              <img src="{{ DEFAULT_THUMBNAIL }}" class="img-fluid">
            {% endif %}
            Banner:
            {% if comic.banner %}
              <img src="{{ comic.banner.url }}" class="img-fluid">
            {% else %}
              <img src="{{ DEFAULT_BANNER }}" class="img-fluid">
            {% endif %}
            <p>Status: {{ comic.get_state_display }}</p>
            <p>Description: {{ comic.description }}</p>
            <p>Created At: {{ comic.created_at|date:"d-m-Y" }}</p>
            <p>Last Update: {{ comic.updated_at|date:"d-m-Y" }}</p>
          </div>
        </div>
      </div>
      <div class="col col-md-9 col-12">
        <author-chapter-container url="{% url 'api_chapter_list_by_comic' comic_slug=comic.slug %}?view=author"></author-chapter-container>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_script %}
<script>
  new Vue({
    el: '#main-content',
  })
</script>
{% endblock %}

webcomic_site/comic/templates/comic/create.html
{% extends 'layouts/main_layout.html' %}

{% block meta_description %}Create your new comic{% endblock %}
{% block meta_keywords %}Comic, Create{% endblock %}
{% block title %}Create New Comic{% endblock %}

{% block content %}
  <div class="container my-3" id="main-content">
    <div class="row justify-content-center">
      <div class="col col-lg-6 col-md-8 col-12">
        <h3>Create New Comic</h3>
        <form method="POST" enctype="multipart/form-data" onsubmit="submitFormAjax(this); return false;" novalidate>
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <button type="submit" class="btn btn-success">Submit</button>
          <a role="button" class="btn btn-secondary" href="{% url 'homepage' %}">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

webcomic_site/comic/templates/comic/create_modal.html
<div class="modal-header">
  <h5 class="modal-title" id="modal-title">New Comic</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<form action="{% url 'comic_create' %}" method="POST" enctype="multipart/form-data" onsubmit="submitFormAjax(this); return false;" novalidate>
  <div class="modal-body">
    {% csrf_token %}
    {% include 'includes/form.html' %}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-success">Submit</button>
  </div>
</form>

webcomic_site/comic/templates/comic/detail.html
{% extends 'layouts/main_layout.html' %}

{% block meta_description %}{{ comic.description }}{% endblock %}
{% block meta_keywords %}Read, Comic, Free, {{ comic.genre.name }}{% endblock %}
{% block title %}{{ comic.title }}{% endblock %}

{% block content %}
  <div class="comic-detail-banner d-none d-md-block">
    {% if comic.banner %}
      <img src="{{ comic.banner.url }}" class="img-fluid" alt="Banner {{ comic.title }}">
    {% else %}
      <img src="{{ DEFAULT_BANNER }}" class="img-fluid" alt="Banner {{ comic.title }}">
    {% endif %}
  </div>

  <div class="container my-3">
    {% if messages %}
      {% include 'includes/alert_message.html' %}
    {% endif %}

    <div class="row">
      <div class="col col-md-9 col-12">
        <h3>{{ comic.title }}</h3>
        <p>
          Genre: <a href="{% url 'genre_detail' slug=comic.genre.slug %}">{{ comic.genre.name }}</a>
          - {{ comic.get_state_display }}
        </p>
        <div class="mt-2" id="main-content">
          <chapter-list-container url="{% url 'api_chapter_list_by_comic' comic_slug=comic.slug %}"></chapter-list-container>
        </div>
      </div>
      <div class="col col-md-3 col-12">
        <div class="mt-2">
          {% if user.is_authenticated %}
            {% if user == comic.author or user.is_superuser %}
              <a role="button" href="{% url 'comic_update' slug=comic.slug %}" class="btn btn-primary">Edit</a>
              <a role="button" href="{% url 'comic_author' slug=comic.slug %}" class="btn btn-primary">Author Page</a>
              {% if comic.state == 0 %}
                <a role="button" href="{% url 'comic_state' slug=comic.slug state=1 %}" class="btn btn-success">Publish</a>
              {% elif comic.state == 1 %}
                <a role="button" href="{% url 'comic_state' slug=comic.slug state=9 %}" class="btn btn-secondary">Archive</a>
              {% else %}
                <a role="button" href="{% url 'comic_state' slug=comic.slug state=0 %}" class="btn btn-secondary">Set to Draft</a>
              {% endif %}
            {% endif %}
          <!--<button class="btn btn-success" id="btn-new-chapter" data-toggle="modal" data-target="#webcomic-modal">-->
            <!--<i class="fas fa-plus-circle"></i> New Chapter-->
          <!--</button>-->
          {% endif %}
          <p>{{ comic.description }}</p>
        </div>
        <div class="comic-detail-thumbnail mt-2">
          {% if comic.thumbnail %}
            <img src="{{ comic.thumbnail.url }}" class="img-fluid">
          {% else %}
            <img src="{{ DEFAULT_THUMBNAIL }}" class="img-fluid">
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_script %}
<script>
  new Vue({
    el: '#main-content',
  })
</script>
{% endblock %}

webcomic_site/comic/templates/comic/update.html
{% extends 'layouts/main_layout.html' %}

{% block extra_meta %}<meta name="robots" content="noindex,nofollow">{% endblock %}
{% block title %}{{ comic.title }}{% endblock %}

{% block content %}
  <div class="container my-3">
    <div class="row justify-content-center">
      <div class="col col-lg-6 col-md-8 col-12">
        <h3>Update {{ comic.title }}</h3>
        <form method="POST" enctype="multipart/form-data" onsubmit="submitFormAjax(this); return false;" novalidate>
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <button type="submit" class="btn btn-success">Update</button>
          <a role="button" class="btn btn-secondary" href="{% url 'comic_detail' slug=comic.slug %}">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}